[2025-07-30T13:48:32.428+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-30T13:48:32.543+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_json_to_doris.truncate_price_change manual__2025-07-29T09:38:10.440119+00:00 [queued]>
[2025-07-30T13:48:32.652+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_json_to_doris.truncate_price_change manual__2025-07-29T09:38:10.440119+00:00 [queued]>
[2025-07-30T13:48:32.666+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-07-30T13:48:33.050+0000] {taskinstance.py:2888} INFO - Executing <Task(SQLExecuteQueryOperator): truncate_price_change> on 2025-07-29 09:38:10.440119+00:00
[2025-07-30T13:48:33.318+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=283) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-30T13:48:33.308+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_json_to_doris', 'truncate_price_change', 'manual__2025-07-29T09:38:10.440119+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/dag_json_to_doris.py', '--cfg-path', '/tmp/tmpvhx2gjct']
[2025-07-30T13:48:33.326+0000] {standard_task_runner.py:105} INFO - Job 71: Subtask truncate_price_change
[2025-07-30T13:48:33.334+0000] {standard_task_runner.py:72} INFO - Started process 297 to run task
[2025-07-30T13:48:56.660+0000] {job.py:229} INFO - Heartbeat recovered after 24.51 seconds
[2025-07-30T13:49:07.018+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_json_to_doris.truncate_price_change manual__2025-07-29T09:38:10.440119+00:00 [running]> on host 980658594ec0
[2025-07-30T13:49:26.964+0000] {job.py:229} INFO - Heartbeat recovered after 36.61 seconds
[2025-07-30T13:49:38.758+0000] {job.py:229} INFO - Heartbeat recovered after 11.91 seconds
[2025-07-30T13:49:38.901+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='reza' AIRFLOW_CTX_DAG_ID='dag_json_to_doris' AIRFLOW_CTX_TASK_ID='truncate_price_change' AIRFLOW_CTX_EXECUTION_DATE='2025-07-29T09:38:10.440119+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-29T09:38:10.440119+00:00'
[2025-07-30T13:49:39.088+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-07-30T13:49:39.112+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-07-30T13:49:39.127+0000] {logging_mixin.py:190} INFO - Current task name:truncate_price_change state:running start_date:2025-07-30 13:48:32.552845+00:00
[2025-07-30T13:49:39.143+0000] {logging_mixin.py:190} INFO - Dag name:dag_json_to_doris and current dag run status:running
[2025-07-30T13:49:39.186+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-07-30T13:49:39.249+0000] {sql.py:266} INFO - Executing: truncate table raw.price_change
[2025-07-30T13:49:39.464+0000] {base.py:84} INFO - Retrieving connection 'mysql_doris_conn'
[2025-07-30T13:49:39.566+0000] {base.py:84} INFO - Retrieving connection 'mysql_doris_conn'
[2025-07-30T13:49:39.676+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 452, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 574, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2025-07-30T13:49:39.856+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-07-30T13:49:39.858+0000] {logging_mixin.py:190} INFO - Task start:2025-07-30 13:48:32.552845+00:00 end:2025-07-30 13:49:39.845405+00:00 duration:67.29256
[2025-07-30T13:49:39.860+0000] {logging_mixin.py:190} INFO - Task:<Task(SQLExecuteQueryOperator): truncate_price_change> dag:<DAG: dag_json_to_doris> dagrun:<DagRun dag_json_to_doris @ 2025-07-29 09:38:10.440119+00:00: manual__2025-07-29T09:38:10.440119+00:00, state:running, queued_at: 2025-07-29 09:38:10.472413+00:00. externally triggered: True>
[2025-07-30T13:49:39.860+0000] {logging_mixin.py:190} INFO - Failure caused by (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2025-07-30T13:49:39.864+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_json_to_doris, task_id=truncate_price_change, run_id=manual__2025-07-29T09:38:10.440119+00:00, execution_date=20250729T093810, start_date=20250730T134832, end_date=20250730T134939
[2025-07-30T13:49:40.757+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-07-30T13:49:40.797+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 71 for task truncate_price_change ((2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)"); 297)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 452, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 574, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/mysql/hooks/mysql.py", line 196, in get_conn
    return MySQLdb.connect(**conn_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)")
[2025-07-30T13:49:41.025+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-30T13:49:41.332+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
